### ISSUE TITLE
Psych JRuby gem seems to have various build and install issues.

### ISSUE THREAD

**Issue by headius** [tenderlove/psych#234]
We've been having trouble getting the Psych gem to build and install consistently.

Sometimes the snakeyaml version number causes a (benign?) error:

```
/Users/headius/projects/psych/lib/psych/versions.rb:2: warning: already initialized constant DEFAULT_SNAKEYAML_VERSION
[INFO] Scanning for projects...
/Users/headius/projects/psych/.tesla.Mavenfile
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project no_group_id_given:psych:0.0.0 (/Users/headius/projects/psych/.tesla.Mavenfile) has 1 error
[ERROR]     'dependencies.dependency.version' for org.yaml:snakeyaml:jar must be a valid version but is '${snakeyaml.version}'.
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

@tenderlove provided a log of his [issues, starting from a clean environment](https://gist.github.com/tenderlove/ad4ebdff32e5d0fa2ee8), with a [command log](https://gist.github.com/tenderlove/c0313b017f6cf55a2e61)

I managed to get things to this point by changing around ruby-maven versions in JRuby and having latest ruby-maven installed, but I have no idea which fixes are good and which are bad.

Help us @mkristian...you're our only hope.

**Comment by headius** [comment]
This is still on the `jruby` branch until @tenderlove says otherwise.

**Comment by mkristian** [comment]
quite often I am hopeless (I am told) but I will do my best ;)

the latest ruby-maven does always spawn a new process for running maven. the older one tries to run maven in the same JVM as JRuby. but looking at the Rakefile it is better to set the ```snakeyaml.version``` via the command-line arguments. will make a PR for this.

then I have the feeling that jruby-9k has problems with some yaml data: https://github.com/jruby/jruby/issues/2910
will try to isolate this more.

**Comment by mkristian** [comment]
actually with #235 and latest ruby-maven this problems is solved.

**Comment by tenderlove** [comment]
I merged #235, but I still can't install.  I'm getting the same errors shown in the log that @headius linked to. :(

**Comment by mkristian** [comment]
@tenderlove did you update ruby-maven ?

**Comment by mkristian** [comment]
and it looks like there is jruby bug involved as well: https://github.com/jruby/jruby/issues/2910

**Comment by tenderlove** [comment]
@mkristian I'm not sure if I updated mavin.  I uninstalled JRuby 9k-pre2 then reinstalled it and rebuilt the gem.  Should I be building from JRuby head?

**Comment by tenderlove** [comment]
Now that I've read jruby/jruby#2910, I think that's the problem I'm hitting too.  Maybe I did update ruby-maven?

**Comment by mkristian** [comment]
no the ruby-maven coming with 9k-pre2 is too old you need to ```gem install ruby-maven``` like all this other gems you need to building psych

**Comment by tenderlove** [comment]
I'm getting a new error now the second time I try to build:

```
[aaron@TC psych (jruby)]$ rake compile
/Users/aaron/git/psych/lib/psych/versions.rb:2: warning: already initialized constant DEFAULT_SNAKEYAML_VERSION
[INFO] Scanning for projects...
/Users/aaron/git/psych/.tesla.Mavenfile
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building psych 0.0.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jruby:jruby:pom:9.0.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.939s
[INFO] Finished at: Wed May 27 13:55:56 PDT 2015
[INFO] Final Memory: 25M/362M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project psych: Could not resolve dependencies for project no_group_id_given:psych:jar:0.0.0: Could not find artifact org.jruby:jruby:pom:9.0.0.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
rake aborted!
No such file or directory - pkg/classpath
org/jruby/RubyIO.java:3592:in `read'
/Users/aaron/git/psych/Rakefile:56:in `block in (root)'
/Users/aaron/git/psych/Rakefile:49:in `block in (root)'
org/jruby/RubyBasicObject.java:1636:in `instance_eval'
/Users/aaron/git/psych/Rakefile:24:in `<top>'
org/jruby/RubyKernel.java:952:in `load'
org/jruby/RubyKernel.java:952:in `load'
(See full trace by running task with --trace)
[aaron@TC psych (jruby)]$ 
```

It looks like the maven part isn't generating the right file.  I guess the POM file is missing, but I don't understand how to fix it.  @mkristian can you give me a hand?  I've pushed all my changes to the jruby branch.

**Comment by mkristian** [comment]
ah - it was a bad idea to pick any jruby version for maven to provide, since the rake-compiler does use the executing jruby anyways. just remove this line:

https://github.com/tenderlove/psych/blob/jruby/Mavenfile#L3

which is by the way the POM (ruby-)maven uses,

but I think this is not needed to fix anymore with
https://github.com/tenderlove/psych/pull/236

**Comment by mkristian** [comment]
the PR #237 is an alternative to #236 and fixes the ruby-maven issue with jruby.

sorry for this - ruby-maven did change drastically since maven-3.3.x does allow to support ruby DSL poms natively and ruby-maven became just  a wrapper around maven-3.3.x but is still buggy. plus all this maven emotions in the jruby team which these problems gave more fuel.

just pick either #236  or #237 to your liking and thanx for you last comment which really helped to fix an severe issue on ruby-maven ;)

**Comment by tenderlove** [comment]
Hi, sorry I haven't updated this.  I merged #237, but I'm still having problems, and I don't know how to debug it.

Here is my environment:

```
[aaron@TC psych (jruby)]$ jruby -v
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 Java HotSpot(TM) 64-Bit Server VM 24.45-b08 on 1.7.0_45-b18 +jit [darwin-x86_64]
[aaron@TC psych (jruby)]$ which mvn
/usr/local/bin/mvn
[aaron@TC psych (jruby)]$ mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
[aaron@TC psych (jruby)]$
```

When I try running `rake clobber`, I get this:

```
[aaron@TC psych (jruby)]$ rake clobber
/Users/aaron/git/psych/lib/psych/versions.rb:2: warning: already initialized constant DEFAULT_SNAKEYAML_VERSION
mvn dependency:build-classpath -Dsnakeyaml.version=1.14 -Dverbose=true
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
rake aborted!
No such file or directory - pkg/classpath
org/jruby/RubyIO.java:3592:in `read'
/Users/aaron/git/psych/Rakefile:58:in `block in (root)'
/Users/aaron/git/psych/Rakefile:49:in `block in (root)'
org/jruby/RubyBasicObject.java:1636:in `instance_eval'
/Users/aaron/git/psych/Rakefile:24:in `<top>'
org/jruby/RubyKernel.java:958:in `load'
org/jruby/RubyKernel.java:958:in `load'
(See full trace by running task with --trace)
[aaron@TC psych (jruby)]$
```

I *think* the error is from `mvn dependency:build-classpath -Dsnakeyaml.version=1.14 -Dverbose=true`, but I'm not sure.

**Comment by tenderlove** [comment]
Apparently this is somehow picking an older JDK. Manually setting $JAVA_HOME like this:

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home
```

Fixed the problem. I can build now.

**Comment by tenderlove** [comment]
I've merged the Java branch and shipped a JRuby version (starting with 2.0.14), so I think we can close this.  Thanks for your help and patience!
